
- ansible.builtin.template:
    src: zprofile.j2
    dest: "{{ ansible_user_dir }}/.zprofile"

- name: Ensure XDG_BASE directories are created
  ansible.builtin.shell:
    cmd: zsh -ic 'mkdir -p $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_DATA_HOME/bin $XDG_STATE_HOME $ZDOTDIR'

- name: Ensure dot dirs exist
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/{{ item | regex_replace(role_path + '/files/') }}"
    state: directory
  with_lines: "find {{ role_path }}/files -mindepth 1 -type d"

- name: Link files into user dir
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item | regex_replace(role_path + '/files/') }}"
    force: yes
    state: link
  with_lines: "find {{ role_path }}/files -mindepth 1 -type f -not -path '*/X11/*' -not -path '*/dunst/*'"
