- name: Ensure dot dirs exist
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/{{ item | regex_replace(role_path + '/files/') }}"
    state: directory
  with_lines: "find {{ role_path }}/files -mindepth 1 -type d"

- name: Link files into user dir
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item | regex_replace(role_path + '/files/') }}"
    force: yes
    state: link
  with_lines: "find {{ role_path }}/files -mindepth 1 -type f"
