- name: Install weechat
  become: true
  dnf:
    name: weechat
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install weechat
  become: true
  pacman:
    name: weechat
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Create weechat directory
  file:
    dest: "{{ ansible_user_dir }}/.weechat"
    state: directory

- name: Link weechat directory
  file:
    src: "{{ dotfiles_dir }}/weechat/{{ item }}"
    dest: "{{ ansible_user_dir }}/.weechat/{{ item }}"
    state: link
    force: yes
  with_items:
    - weechat.conf
    - trigger.conf
    - irc.conf
