---

- name: Download go tarball
  unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ xdg_data_home }}"
    copy: no

- name: Ensure go directories exist
  file:
    dest: "{{ ansible_user_dir }}/go/{{ item }}"
    state: directory
  with_items:
    - bin
    - pkg
    - src

- name: Link configuration files into zdotdir
  file:
    src: "{{ item }}"
    dest: "{{ zdotdir }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*.zsh"

- name: Install important go mods
  shell: "GO111MODULE=on go get {{ item }}"
  with_items:
    - "golang.org/x/tools/gopls@latest"
    - "gotest.tools/gotestsum"
    - "github.com/axw/gocov/..."
    - "github.com/AlekSi/gocov-xml"
    - "golang.org/x/tools/cmd/goimports"
