---

- name: Install common ArchLinux packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    # Very common
    - dnsmasq
    - imagemagick
    - make
    - openssl
    - openssh
    - openvpn
    - ripgrep
    - rsync
    - scrot
    - xsel
    - wget
    # Input
    - xf86-input-synaptics
    # Networking + Wireless
    - iw
    - wpa_supplicant
    - linux-headers
    - broadcom-wl-dkms
    - networkmanager
    - network-manager-applet
    # Video
    - nvidia
    - nvidia-settings
    - mesa
    - libva-intel-driver
    - libva
    # Power management
    - lm_sensors
    - tlp
    # Sound management
    - alsa-utils
    # Bluetooth
    - bluez
    - bluez-utils
    # Intel microcode updates
    - intel-ucode

- name: Activate/Deactivate Services
  become: true
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: "{{ item.masked }}"
  with_items:
    - { name: lightdm, enabled: yes, masked: no }
    - { name: dhcpcd, enabled: no, masked: no }
    - { name: NetworkManager, enabled: yes, masked: no }
    - { name: lm_sensors, enabled: yes, masked: no }
    - { name: fancontrol, enabled: yes, masked: no }
    - { name: tlp, enabled: yes, masked: no }
    - { name: tlp-sleep, enabled: yes, masked: no }
    - { name: bluetooth, enabled: yes, masked: no }
    - { name: systemd-rfkill.service, enabled: no, masked: yes }
    - { name: systemd-rfkill.socket, enabled: no, masked: yes }

- name: Install fonts
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - adobe-source-code-pro-fonts
    - ttf-dejavu
    - ttf-fira-mono
    - ttf-inconsolata
    - ttf-ubuntu-font-family

#- name: Install linux-macbook kernel
#  block:
#    - name: Update pacman.conf
#      become: true
#      blockinfile:
#        path: /etc/pacman.conf
#        block: |
#          [linux-macbook]
#          SigLevel = Optional TrustAll
#          Server = http://libpcap.net/repo/linux-macbook
#    - name: Update pacman cache
#      become: true
#      pacman:
#        update_cache: yes
#    - name: Clone/Update linux-macbook project
#      git:
#        repo: "https://aur.archlinux.org/linux-macbook.git"
#        dest: "{{ ansible_user_dir }}/aur_packages/linux-macbook"
#        update: yes
