---

- name: Install common ArchLinux packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    # Very common
    - make
    - openssl
    - openssh
    - ripgrep
    - rsync
    - scrot
    - xsel
    # Input
    - xf86-input-synaptics
    # Networking + Wireless
    - iw
    - wpa_supplicant
    - linux-headers
    - broadcom-wl-dkms
    - networkmanager
    - network-manager-applet
    # Video
    - xf86-video-intel
    - mesa-libgl
    - libva-intel-driver
    - libva

- name: Activate/Deactivate Services
  become: true
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: no
  with_items:
    - { name: lightdm, enabled: yes }
    - { name: dhcpcd, enabled: no }
    - { name: NetworkManager, enabled: yes }

- name: Install fonts
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - adobe-source-code-pro-fonts
    - ttf-dejavu
    - ttf-fira-mono
    - ttf-inconsolata
    - ttf-ubuntu-font-family
