---

- name: Install common ArchLinux packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    # Very common
    - imagemagick
    - make
    - openssl
    - openssh
    - openvpn
    - ripgrep
    - rsync
    - scrot
    - xsel
    - wget
    # Input
    - xf86-input-synaptics
    # Networking + Wireless
    - iw
    - wpa_supplicant
    - linux-headers
    - broadcom-wl-dkms
    - networkmanager
    - network-manager-applet
    # Video
    - xf86-video-intel
    - xf86-video-nouveau
    - mesa
    - libva-intel-driver
    - libva
    # Power management
    - lm_sensors
    - tlp
    # Sound management
    - alsa-utils
    # Bluetooth
    - bluez
    - bluez-utils
    # Intel microcode updates
    - intel-ucode

- name: Activate/Deactivate Services
  become: true
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: "{{ item.masked }}"
  with_items:
    - { name: lightdm, enabled: yes, masked: no }
    - { name: dhcpcd, enabled: no, masked: no }
    - { name: NetworkManager, enabled: yes, masked: no }
    - { name: lm_sensors, enabled: yes, masked: no }
    - { name: fancontrol, enabled: yes, masked: no }
    - { name: tlp, enabled: yes, masked: no }
    - { name: tlp-sleep, enabled: yes, masked: no }
    - { name: bluetooth, enabled: yes, masked: no }
    - { name: systemd-rfkill.service, enabled: no, masked: yes }
    - { name: systemd-rfkill.socket, enabled: no, masked: yes }

- name: Install fonts
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - adobe-source-code-pro-fonts
    - ttf-dejavu
    - ttf-fira-mono
    - ttf-inconsolata
    - ttf-ubuntu-font-family
