---

- name: Install necessary repos
  become: true
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: yes
    gpgcheck: yes
  with_items:
    - name: google-chrome
      description: The google chrome repository
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
      gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    - name: virtualbox
      description: The virtual box repository
      baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
      gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Install the rpmfusion repo packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  when: ansible_os_family == "RedHat"

- name: Install common RedHat packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ packages }}"
  when: ansible_os_family == "RedHat"

- name: Install headers
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel-devel
    - kernel-headers
  when: ansible_os_family == "RedHat"


- name: Install fonts
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ fonts }}"
  when: ansible_os_family == "RedHat"
