---

services:
    - docker

language: python
python: "2.7"

branches:
  only:
    - master

env:
  global:
    - ANSIBLE_VERSION=latest
  matrix:
    - OS=fedora DIST=24
    - OS=fedora DIST=25
    - OS=fedora DIST=26

before_install:
  - sudo dnf upgrade

install:
  - pip install ansible

script:
  - ansible-playbook -i ansible-setup/inventory ansible-setup/fedora.yaml --syntax-check
  - ansible-playbook -i ansible-setup/inventory ansible-setup/fedora.yaml -vvvv
