---

sudo: required
os: fedora
dist: 26

language: python
python: "2.7"

branches:
  only:
    - master

env:
  - ANSIBLE_VERSION=latest

before_install:
  - sudo dnf upgrade

install:
  - pip install ansible

script:
  - ansible-playbook -i ansible-setup/inventory ansible-setup/fed26.yaml --syntax-check
  - ansible-playbook -i ansible-setup/inventory ansible-setup/fed26.yaml -vvvv
