---

language: python
python: "2.7"
sudo: required
services:
  - docker

git:
  submodules: false

branches:
  only:
    - master

env:
  global:
    - ANSIBLE_VERSION=latest
  matrix:
    - OS=fedora DIST=24
    - OS=fedora DIST=25
    - OS=fedora DIST=26

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - docker pull ${OS}:${DIST}
  - container_id=$(docker run --detach --volume=${PWD}:/workspace:ro ${OS}:${DIST} /bin/sh & )

install:
  - docker exec ${container_id} sudo dnf upgrade
  - docker exec ${container_id} sudo dnf install python
  - docker exec ${container_id} pip install ansible

script:
  - >
    docker exec --tty ${container_ id} env TERM=xterm
    ansible-playbook -i /workspace/ansible-setup/inventory /workspace/ansible-setup/fedora.yaml --syntax-check
  - >
    docker exec --tty ${container_id} env TERM=xterm
    ansible-playbook -i /workspace/ansible-setup/inventory /workspace/ansible-setup/fedora.yaml -vvvv
