---

- hosts: localhost
  vars:
    workspace_dir: "{{ lookup('env', 'WORKSPACE') | default(ansible_user_dir ~ '/Workspace', true) }}"
    xdg_cache_home: "{{ lookup('env', 'XDG_CACHE_HOME') | default(ansible_user_dir ~ '/.cache', true) }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_user_dir ~ '/.local/share', true) }}"
    scripts_dir: "{{ ansible_user_dir ~ '/.local/share/bin' }}"
    zdotdir: "{{ lookup('env', 'ZDOTDIR') | default(xdg_config_home ~ '/zsh', true) }}"
    hostname: "dz-thinkpad"
  pre_tasks:
    - name: Upgrade all installed packages
      become: true
      dnf:
        name: "*"
        state: latest
      tags:
        - always
    - name: Ensure essential directories exist
      file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "{{ workspace_dir }}"
        - "{{ xdg_cache_home }}"
        - "{{ xdg_config_home }}"
        - "{{ xdg_data_home }}"
        - "{{ scripts_dir }}"
      tags:
        - always
  roles:
    # Essentials
    - { role: git, tags: [ 'git' ] }
    - { role: gpg, tags: [ 'gpg' ] }
    - { role: common, tags: [ 'common' ] }
    - { role: zsh, tags: [ 'zsh' ] }
    - { role: base16-shell, tags: [ 'base16-shell' ] }
    - { role: fonts, tags: [ 'fonts' ] }
    - { role: fzf, tags: [ 'fzf' ] }
    - { role: tmux, tags: [ 'tmux' ] }
    - { role: ripgrep, tags: [ 'ripgrep' ] }
    - { role: nvim, tags: [ 'nvim' ] }
    - { role: scripts, tags: [ 'scripts' ] }
    # Languages
    - { role: golang, tags: [ 'golang' ] }
    - { role: rust, tags: [ 'rust' ] }
    # Display
    - { role: dwm, tags: [ 'dwm' ] } # depends on st, sxhkd, dunst
    - { role: sxiv, tags: [ 'sxiv' ] }
    # K8s Stuff
    - { role: container-tools, tags: [ 'container-tools' ] }
    - { role: crc, tags: [ 'crc' ] }
    - { role: kubedev, tags: [ 'kubedev' ] }
    - { role: ocp, tags: [ 'ocp' ] }
    - { role: minikube, tags: [ 'minikube' ] }
    # Work stuff
    - { role: ansible, tags: [ 'ansible' ] }
    - { role: redhat, tags: [ 'redhat' ] }
