---

- hosts: localhost
  vars:
    workspace_dir: "{{ lookup('env', 'WORKSPACE') | default(ansible_user_dir ~ '/Workspace', true) }}"
    xdg_cache_home: "{{ lookup('env', 'XDG_CACHE_HOME') | default(ansible_user_dir ~ '/.cache', true) }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_user_dir ~ '/.local/share', true) }}"
  pre_tasks:
    - name: Upgrade all installed packages
      become: true
      dnf:
        name: "*"
        state: latest
    - name: Ensure workspace directory exists
      file:
        dest: "{{ workspace_dir }}"
        state: directory
  roles:
    - { role: common, tags: [ 'common' ] }
    - { role: git, tags: [ 'git' ] }
    - { role: scripts, tags: [ 'scripts' ] }
    - { role: dwm, tags: [ 'dwm' ] } # depends on st, sxhkd, dunst
    - { role: zsh, tags: [ 'zsh' ] }
    - { role: fzf, tags: [ 'fzf' ] }
    - { role: vim, tags: [ 'vim' ] }
    - { role: tmux, tags: [ 'tmux' ] }
    - { role: ripgrep, tags: [ 'ripgrep' ] }
    - { role: gpg, tags: [ 'gpg' ] }
    - { role: wallpapers, tags: [ 'wallpapers' ] }
    - { role: sxiv, tags: [ 'sxiv' ] }
