---

- hosts: localhost
  vars:
    workspace_dir: "{{ lookup('env', 'WORKSPACE') | default(ansible_user_dir ~ '/Workspace', true) }}"
    xdg_cache_home: "{{ lookup('env', 'XDG_CACHE_HOME') | default(ansible_user_dir ~ '/.cache', true) }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_user_dir ~ '/.local/share', true) }}"
    zdotdir: "{{ lookup('env', 'ZDOTDIR') | default(ansible_user_dir ~ '/.config/zsh', true) }}"
  pre_tasks:
    - name: Upgrade all installed packages
      become: true
      dnf:
        name: "*"
        state: latest
    - name: Ensure workspace directory exists
      file:
        dest: "{{ workspace_dir }}"
        state: directory
  roles:
    # Shell stuff
    - { role: zsh, tags: [ 'zsh' ] }
    - { role: base16-shell, tags: [ 'base16-shell' ] }
    - { role: fonts, tags: [ 'fonts' ] }
    - { role: git, tags: [ 'git' ] }
    - { role: fzf, tags: [ 'fzf' ] }
    - { role: tmux, tags: [ 'tmux' ] }
    - { role: gpg, tags: [ 'gpg' ] }
    - { role: ripgrep, tags: [ 'ripgrep' ] }
    - { role: scripts, tags: [ 'scripts' ] }
    # Common
    - { role: common, tags: [ 'common' ] }
    # K8s Stuff
    - { role: container-tools, tags: [ 'container-tools' ] }
    - { role: crc, tags: [ 'crc' ] }
    - { role: golang, tags: [ 'golang' ] }
    - { role: kubedev, tags: [ 'kubedev' ] }
    # - { role: ocp, tags: [ 'ocp' ] }
    # - { role: minikube, tags: [ 'minikube' ] }
    # Work stuff
    - { role: ansible, tags: [ 'ansible' ] }
    - { role: redhat, tags: [ 'redhat' ] }
    - { role: nvim, tags: [ 'nvim' ] }
    # Misc
    # - { role: dwm, tags: [ 'dwm' ] } # depends on st, sxhkd, dunst
    # - { role: wallpapers, tags: [ 'wallpapers' ] }
    # - { role: sxiv, tags: [ 'sxiv' ] }
