---

- name: Get packages for building/using dwm
  become: true
  dnf:
    state: latest
    name:
      - dmenu
      - dbus-x11
      - feh
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - picom
      - xorg-x11-apps
      - xorg-x11-xinit-session
      - xorg-x11-server-Xorg
      - xorg-x11-server-common
      - xorg-x11-xinit

- name: Pull dwm
  git:
    repo: git@github.com:djzager/dwm
    dest: "{{ dwm_dir }}"
    update: no

- name: Add upstream remote
  command: git remote add up https://git.suckless.org/dwm
  args:
    chdir: "{{ dwm_dir }}"
  register: command_result
  failed_when: "command_result.rc != 0 and 'remote up already exists' not in command_result.stderr"
  changed_when: command_result.rc == 0

# - name: Build dwm
#   become: true
#   make:
#     chdir: "{{ dwm_dir }}"
#     target: install

- name: Link xinitrc into place
  file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: Link bash profile to .profile
  file:
    src: "{{ ansible_user_dir }}/.profile"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    force: yes
    state: link
  with_items:
   - bash_profile
   - zprofile
