#!/usr/bin/env sh

command=$1

backlight_path="/sys/class/backlight/intel_backlight"
brightness_path="${backlight_path}/brightness"
max_brightness_path="${backlight_path}/max_brightness"

brightness_step=50
min_brightness=1
cur_brightness=$(<${brightness_path})
max_brightness=$(<${max_brightness_path})

case $1 in
	min)
		sudo tee ${brightness_path} <<<${min_brightness}
		;;
	-)
		new_brightness=$[$cur_brightness-$brightness_step]
		if [ $new_brightness -lt $min_brightness ]; then
			sudo tee ${brightness_path} <<<${min_brightness}
		else
			sudo tee ${brightness_path} <<<${new_brightness}
		fi
		;;
	+)
		new_brightness=$[$cur_brightness+$brightness_step]
		if [ $new_brightness -gt $max_brightness ]; then
			sudo tee ${brightness_path} <${max_brightness_path}
		else
			sudo tee ${brightness_path} <<<${new_brightness}
		fi
		;;
	max)
		sudo tee ${brightness_path} <${max_brightness_path}
		;;
	*)
		echo "min, +, -, max only are accepted"
		exit 1
esac
