#!/usr/bin/env sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

chosen=$(grep -vi "### EMOJIS ###" "$HOME/.config/emoji" | dmenu -i -l 20 -fn Monospace-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | awk '{ print $1 }')
echo "$c" | xargs -I {} printf {} | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &
