---

- name: Install common RedHat packages
  become: true
  dnf:
    state: latest
    name:
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome

- name: Check if RedHat packages are installed
  package_facts:
    manager: "auto"

- name: Pause to setup VPN
  pause:
    prompt: "https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0005424"
  when: "'redhat-internal-cert-install' not in ansible_facts.packages"

- name: Copy repos into place
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/files/repos/*"

- name: Install redhat related tools
  become: true
  dnf:
    state: latest
    enablerepo: rcm-tools-fedora-rpms
    name:
      - rhpkg
      - krb5-workstation

- name: Copy krb5 conf file into place
  become: true
  copy:
    src: "{{ role_path }}/files/krb5.conf"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: '0644'

- name: Create chrome policies dir
  become: true
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: '0755'

- name: Enable kerberos auth in chrome
  become: true
  copy:
    src: "{{ role_path }}/files/redhat-corp.json"
    dest: "/etc/opt/chrome/policies/managed/redhat-corp.json"
    owner: root
    group: root
    mode: '0644'
