---

- name: Copy repos into place
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/files/repos/*"


- name: Install redhat related tools
  become: true
  dnf:
    state: latest
    name:
      - rhpkg
      - krb5-workstation

- name: Copy krb5 conf file into place
  become: true
  copy:
    src: "{{ role_path }}/files/krb5.conf"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: '0644'

- name: Enable kerberos auth in chrome
  become: true
  copy:
    src: "{{ role_path }}/files/redhat-corp.json"
    dest: "/etc/opt/chrome/policies/managed/redhat-corp.json"
    owner: root
    group: root
    mode: '0644'
