#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f $HOME/.xprofile ] && . $HOME/.xprofile

while :; do
	#dbus-launch --exit-with-session dwm || break
	ssh-agent dwm || break
done
