#!/usr/bin/env sh

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# https://wiki.archlinux.org/index.php/Qt
export QT_QPA_PLATFORMTHEME="qt5ct"

# https://wiki.archlinux.org/title/Cursor_themes#X_resources
[ -f ~/.Xresources ] && xrdb ~/.Xresources &

setbg &                     # Set the background
sxhkd &                     # Bind keys
dunst &                     # Notification daemon
picom --daemon --config=/dev/null --experimental-backends --backend glx --vsync --blur-method="dual_kawase" --blur-size="2" # Transparency
xset dpms 600 &             # Sleep after 10 minutes
xset r rate 300 50 &        # Speed xrate up
