#!/usr/bin/env sh

# https://wiki.archlinux.org/index.php/Qt
export QT_QPA_PLATFORMTHEME="qt5ct"

(setbg) &                     # Set the background
(sxhkd) &                     # Bind keys
(dunst) &                     # Notification daemon
# (xcompmgr) &                  # Transparency
(xset dpms 600) &             # Sleep after 10 minutes
(xset r rate 300 50) &        # Speed xrate up
(synclient TouchPadOff=1) &   # Turn the touchpad off
# Dunst
# systemctl --user set-environment &
# systemctl --user import-environment DISPLAY &
# systemctl --user start dunst &

# while true; do
# 	xsetroot -name "$(date +'%F %R')"
# 	sleep 30s
# done &
