#!/usr/bin/env sh

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# https://wiki.archlinux.org/index.php/Qt
export QT_QPA_PLATFORMTHEME="qt5ct"

setbg &                     # Set the background
sxhkd &                     # Bind keys
dunst &                     # Notification daemon
picom &                     # Transparency
xset dpms 600 &             # Sleep after 10 minutes
xset r rate 300 50 &        # Speed xrate up
