---

- name: Install virtualization
  become: true
  dnf:
    state: latest
    name:
      - "@virtualization"

- name: Enable libvirt
  become: true
  systemd:
    name: libvirtd
    state: started
    enabled: True

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
    append: yes
