---

- hosts: localhost
  vars:
    dotfiles_dir: "{{ playbook_dir | regex_replace('/ansible-setup', '') }}"
    packages:
      - asciinema
      - aspell
      - aspell-en
      - cscope
      - ctags
      - direnv
      - gcc
      - gdb
      - google-chrome-stable
      - htop
      - ImageMagick
      - java
      - libselinux-python
      - make
      - node
      - openssl
      - openssh
      - patch
      - python-virtualenv
      - rsync
      - scrot
      - telegram-desktop
      - tree
      - vagrant
      - VirtualBox-5.1
      - valgrind
      - weechat
      - xbacklight
      - xorg-x11-drv-synaptics-legacy
      - xsel
    fonts:
      - adobe-source-code-pro-fonts
  pre_tasks:
    - name: Upgrade all installed packages
      become: true
      dnf:
        name: "*"
        state: latest
  roles:
    - { role: asb-dev, tags: [ 'asb-dev' ] }
    - { role: atom, tags: [ 'atom' ] }
    - { role: common, tags: [ 'common' ] }
    - { role: docker, tags: [ 'docker' ] }
    - { role: dunst, tags: [ 'dunst' ] }
    - { role: fzf, tags: [ 'fzf' ] }
    - { role: git, tags: [ 'git' ] }
    - { role: golang, tags: [ 'golang' ] }
    - { role: i3, tags: [ 'i3' ] }
    - { role: oh-my-zsh, tags: [ 'oh-my-zsh' ] }
    - { role: tmux, tags: [ 'tmux' ] }
    - { role: vim, tags: [ 'vim' ] }
    - { role: weechat, tags: [ 'weechat' ] }
