---

- hosts: localhost
  vars:
    dotfiles_dir: "{{ playbook_dir | regex_replace('/ansible-setup', '') }}"
    packages:
      - asciinema
      - cscope
      - ctags
      - direnv
      - gcc
      - gdb
      - google-chrome-stable
      - htop
      - ImageMagick
      - java
      - libselinux-python
      - make
      - node
      - openssl
      - openssh
      - patch
      - rsync
      - scrot
      - tree
      - vagrant
      - VirtualBox-5.1
      - valgrind
      - weechat
      - xbacklight
      - xorg-x11-drv-synaptics-legacy
      - xsel
    fonts:
      - adobe-source-code-pro-fonts
  pre_tasks:
    - name: Upgrade all installed packages
      become: true
      dnf:
        name: "*"
        state: latest
  roles:
    - asb-dev
    - atom
    - common
    - docker
    - fzf
    - git
    - golang
    - i3
    - oh-my-zsh
    - tmux
    - vim
