---

- hosts: localhost
  vars:
    dotfiles_dir: "{{ playbook_dir | regex_replace('/ansible-setup', '') }}"
  roles:
    # - osx
    - { role: atom, tags: [ 'atom' ] }
    - { role: common, tags: ['common'] }
    - { role: docker, tags: [ 'docker' ] }
    - { role: fzf, tags: [ 'fzf' ] }
    - { role: git, tags: [ 'git' ] }
    - { role: golang, tags: [ 'golang' ] }
    - { role: oh-my-zsh, tags: [ 'oh-my-zsh' ] }
    - { role: tmux, tags: [ 'tmux' ] }
    #- { role: vagrant, tags: [ 'vagrant' ] }
    - { role: vim, tags: [ 'vim' ] }
    #- { role: weechat, tags: [ 'weechat' ] }
    #- { role: znc, tags: [ 'znc' ] }
