#!/usr/bin/env bash

set -e # Exit immediately on failure
set -x # Show commands

OCP_CONFIG_DIR=${OCP_CONFIG_DIR:-"$XDG_CONFIG_HOME/ocp"}
OCP_INSTALL_CONFIG=${OCP_INSTALL_CONFIG:-"$OCP_CONFIG_DIR/install-aws-config.yaml"}
CLUSTER_NAME=${CLUSTER_NAME:="my-cluster"}
CLUSTER_DIR="${OCP_CONFIG_DIR}/${CLUSTER_NAME}"

export AWS_PROFILE="openshift-dev"
export AWS_SDK_LOAD_CONFIG="${XDG_CONFIG_HOME}/aws"

create_cluster() {
  mkdir -p "${CLUSTER_DIR}"
  cp "${OCP_INSTALL_CONFIG}" "${CLUSTER_DIR}/install-config.yaml"
  openshift-install --dir "${CLUSTER_DIR}" create cluster
  if [ $? -eq 0 ]; then
    export KUBECONFIG="${CLUSTER_DIR}/auth/kubeconfig"
    oc login -u kubeadmin -p $(</"${CLUSTER_DIR}/auth/kubeadmin-password")
    if [ $? -eq 0 ]; then
      xclip -selection clipboard "${CLUSTER_DIR}/auth/kubeadmin-password"
      notify-send "cluster up, password copied to clipboard"
      xclip -selection primary "Foo"
      notify-send "cluster up, foo copied to primary"
    fi
  fi
}

destroy_cluster() {
  openshift-install --dir "${CLUSTER_DIR}" destroy cluster
  rm -rf my-cluster
}

case $1 in
create)
  create_cluster
  ;;
destroy)
  destroy_cluster
  ;;
*)
  echo "Must be either create or destroy"
  exit 1
  ;;
esac
