alias gc='git commit -v'
alias gcm='git checkout master'
alias gco='git checkout'
alias gd='git diff'
alias gst='git status'
alias gp='git push'
alias gpf='git push --force'
alias gpfu='git push --force --set-upstream'
