---

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - arc-gtk-theme
    - arc-icon-theme
  when: ansible_os_family == "Archlinux"
