---

- name: Enable zsh-autosuggestions repo (CentOS)
  become: true
  command: dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:zsh-users:zsh-autosuggestions/CentOS_8_Stream/shells:zsh-users:zsh-autosuggestions.repo
  args:
    creates: /etc/yum.repos.d/zsh-autosuggestions.repo
  when: ansible_distribution == "CentOS"

- name: Install zsh
  become: true
  dnf:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: latest

- name: Set default shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Ensure zsh config and cache directories exists
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ zsh_config_dir }}"
    - "{{ zsh_cache_dir }}"

- name: Link profile into place
  file:
    src: "{{ role_path }}/files/profile"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    force: yes
    state: link
  with_items:
    - "profile"
    - "zprofile"

- name: Link zshrc into place
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ zsh_config_dir }}/.zshrc"
    force: yes
    state: link

- name: Link configurations into config dir
  file:
    src: "{{ item }}"
    dest: "{{ zsh_config_dir }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*.zsh"
