---

- name: Install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - i3
    - i3status
    - dmenu
    - i3lock
    - xbacklight
    - feh
    - conky
  when: ansible_os_family == "RedHat"

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - i3
    - i3status
    - dmenu
    - i3lock
    - xorg-server
    - xorg-xbacklight
    - xorg-xhost
    - xorg-xrandr
    - feh
    - conky
  when: ansible_os_family == "Archlinux"

- name: Make sure .config directories exists
  file:
    dest: "{{ ansible_user_dir }}/{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - .config/i3
    - .config/i3status

- name: Link configuration files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: "{{ dotfiles_dir }}/i3/config"
      dest: "{{ ansible_user_dir }}/.config/i3/config"
    - src: "{{ dotfiles_dir }}/i3/status"
      dest: "{{ ansible_user_dir }}/.config/i3status/config"
