---

- name: Install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - i3
    - i3status
    - dmenu
    - i3lock
    - xbacklight
    - feh
    - conky
  when: ansible_os_family == "RedHat"

- name: Make sure .config directory exists
  file:
    dest: "{{ ansible_user_dir }}/.config/i3"
    recurse: yes
    state: directory

- name: Link configuration files
  file:
    src: "{{ dotfiles_dir }}/i3/config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    state: link
