---

- name: Create temp directory for crc archive
  file:
    path: "{{ crc_dir }}"
    state: directory

- name: Get crc archive
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz"
    dest: "{{ crc_dir }}/crc-linux-amd64.tar.xz"
  register: crc_tar

- name: Unarchive crc
  unarchive:
    src: "{{ crc_tar.dest }}"
    dest: "{{ crc_dir }}"
    extra_opts: [--strip-components=1]

- name: Link crc
  file:
    src: "{{ crc_dir }}/crc"
    path: "{{ xdg_data_home }}/bin/crc"
    state: link
