---

- name: Download oc
  unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-{{ oc_version }}/openshift-client-linux.tar.gz"
    dest: "{{ xdg_data_home }}/bin"
    copy: no

- name: Download openshift-installer
  unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-{{ oc_version }}/openshift-install-linux.tar.gz"
    dest: "{{ xdg_data_home }}/bin"
    copy: no

- name: Link scripts into place
  file:
    src: "{{ item }}"
    dest: "{{ xdg_data_home }}/bin/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*"
