---

- name: Pull zsh
  git:
    repo: git@github.com:junegunn/fzf
    dest: "{{ fzf_dir }}"
    update: yes

- name: Install fzf
  shell: ./install --bin
  args:
    chdir: "{{ fzf_dir }}"

- name: Link fzf to xdg_data_home bin
  file:
    src: "{{ fzf_dir }}/bin/{{ item }}"
    dest: "{{ xdg_data_home }}/bin/{{ item }}"
    force: yes
    state: link
  with_items:
    - fzf
    - fzf-tmux

- name: Link fzf completion & keybindings to zdotdir
  file:
    src: "{{ fzf_dir }}/shell/{{ item }}"
    dest: "{{ zdotdir }}/fzf-{{ item }}"
    force: yes
    state: link
  with_items:
    - completion.zsh
    - key-bindings.zsh
