---

- name: Install Dunst
  become: true
  dnf:
    state: latest
    name:
      - dunst

- name: Ensure config directory exists
  file:
    dest: "{{ dunst_config_dir }}"
    state: directory

- name: Link dunstrc into place
  file:
    src: "{{ role_path }}/files/dunstrc"
    dest: "{{ dunst_config_dir }}/dunstrc"
    force: yes
    state: link
