---

- name: Install
  become: true
  dnf:
    name: git
    state: latest
  when: ansible_os_family == "RedHat"

- name: Link configuration files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: "{{ dotfiles_dir}}/git/config"
      dest: "{{ ansible_user_dir }}/.gitconfig"
    - src: "{{ dotfiles_dir}}/git/ignore"
      dest: "{{ ansible_user_dir }}/.gitignore"
