---

- name: Install needed python packages
  become: true
  dnf:
    state: latest
    name:
      - python3
      - python3-pip

- name: Install needed python packages
  become: true
  pip:
    state: latest
    name:
      - openshift
