---

- name: Install golangci-lint
  vars:
    golangci_download_dir: "{{ xdg_data_home }}/golangci-lint-{{ golangci_version }}-linux-amd64"
    golangci_final: "{{ xdg_data_home }}/bin/golangci-lint"
  block:
    - name: Download golangci-lint release
      unarchive:
        src: "https://github.com/golangci/golangci-lint/releases/download/v{{ golangci_version }}/golangci-lint-{{ golangci_version }}-linux-amd64.tar.gz"
        dest: "{{ xdg_data_home }}"
        copy: no

    - name: Move golangci-lint into $XDG_DATA_HOME/bin
      command: "mv {{ golangci_download_dir }}/golangci-lint {{ golangci_final }}"

    - name: Remove golangci-lint directory
      file:
        path: "{{ golangci_download_dir }}"
        state: absent

- name: Install kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ xdg_data_home }}/bin/kubectl"
    force: yes

- name: Install kubebuilder
  vars:
    kubebuilder_archive_dir: "kubebuilder_{{ kubebuilder_version }}_linux_amd64"
    kubebuilder_dir: "{{ xdg_data_home }}/kubebuilder"
  block:
    - name: Create temp directory for kubebuilder archive
      tempfile:
        state: directory
      register: kubebuilder

    - name: Get kubebuilder archive
      get_url:
        url: "https://go.kubebuilder.io/dl/{{ kubebuilder_version }}/linux/amd64"
        dest: "{{ kubebuilder.path }}"
      register: kubebuilder_tar

    - name: Unarchive kubebuilder
      unarchive:
        src: "{{ kubebuilder_tar.dest }}"
        dest: "{{ kubebuilder.path }}"

    - name: Remove existing kubebuilder bin directory
      file:
        path: "{{ kubebuilder_dir }}"
        state: absent

    - name: Move kubebuilder into place
      command: "mv -f {{ kubebuilder.path }}/{{ kubebuilder_archive_dir }} {{ kubebuilder_dir }}"

    - name: Remove temp directory
      file:
        path: "{{ kubebuilder.path }}"
        state: absent

- name: Link configuration files into zdotdir
  file:
    src: "{{ item }}"
    dest: "{{ zdotdir }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*.zsh"
