---

- name: Install tmux
  become: true
  dnf:
    name: tmux
    state: latest

- name: Link tmux config into place
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    force: yes
    state: link
