#!/bin/bash

set -e

DOCKED=$1
INTERNAL="eDP1"
EXTERNAL="DP2-1"

if $DOCKED; then
    /usr/bin/xrandr --output ${INTERNAL} --off --output ${EXTERNAL} --auto
else
    /usr/bin/xrandr --output ${EXTERNAL} --off --output ${INTERNAL} --auto
fi

feh --bg-fill ~/wallpaper
