#!/bin/bash

set -e

INTERNAL="eDP1"
EXTERNAL="DP2-1"
HDMI="HDMI1"

if /usr/bin/xrandr | grep "${EXTERNAL} connected"; then
    /usr/bin/xrandr --output ${INTERNAL} --off --output ${EXTERNAL} --auto
elif /usr/bin/xrandr | grep "${HDMI} connected"; then
    /usr/bin/xrandr --output ${INTERNAL} --auto --output ${HDMI} --auto --above ${INTERNAL}
else
    /usr/bin/xrandr --output ${EXTERNAL} --off --output ${HDMI} --off --output ${INTERNAL} --auto
fi

feh --bg-fill ~/wallpaper
