#!env bash
IMAGE=/tmp/i3lock.png
PAD=pad.png
BACKGROUND=$HOME/wallpaper

# convert $BACKGROUND -scale 25% -blur 0x20 -scale 400% $IMAGE
composite -gravity center $PAD $BACKGROUND $IMAGE

i3lock -i $IMAGE
rm $IMAGE
