#!env bash
IMAGE=/tmp/i3lock.png
PAD=$HOME/Pictures/pad.png
BACKGROUND=$HOME/wallpaper

convert $BACKGROUND $IMAGE
# composite -size 2560x1440 -gravity center $PAD $IMAGE $IMAGE
# composite -size 2560x1440 -gravity center $PAD $BACKGROUND $IMAGE

i3lock -i $IMAGE
rm $IMAGE
