---

#- include_tasks: "{{ ansible_os_family }}.yaml"

- ansible.builtin.debug:
    msg: "This is {{ ansible_os_family }}"

- name: Install common packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - avahi
      - nss-mdns
      - bat
      - cups
      - dunst
      - feh
      - flameshot
      - fuse-overlayfs # for podman
      - git
      - github-cli  # gh cli tool for interacting with GH repos
      - imagemagick # image manipulator
      - jq
      - yq
      - lvm2
      - maim        # Screenshot
      - mediainfo
      - minikube
      - mpv
      - neovim
      - networkmanager
      - networkmanager-openvpn
      - noto-fonts-emoji
      - pipewire
      - pipewire-pulse
      - docker
      - podman
      - pulsemixer
      - ripgrep
      - rust
      - slirp4netns
      - starship
      - sudo
      - sxhkd
      - sxiv
      - telegram-desktop
      - tmux
      - tree
      - vlc
      - wget
      - xclip
      - xdg-user-dirs
      - xdg-utils
      - xorg
      - xprintidle # consider xidlehook
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      # GPG stuff
      - gnupg
      # JS Stuff
      - nodejs
      - npm
      - typescript
      - yarn
      - krb5
      # Camera as webcam stuff
      - gphoto2
      - v4l2loopback-utils
      - v4l2loopback-dkms

- name: Install yay (and packages)
  ansible.builtin.include_role:
    name: jahrik.yay
  vars:
    install: true
    aur_packages:
      - brave-bin
      - fzf-git
      - lf-git
      - picom-git
      - nvim-packer-git
      - slack-desktop
      # Kube stuff
      - kind
      - kubectl-bin
      - openshift-client-bin
      - krew-bin
      - podman-desktop
      - operator-sdk
  tags:
    - 'aur'

- name: Enable (and start) common services
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - avahi-daemon.service
    - cups.socket
