---

- name: Copy repos into place
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/files/repos/*"

- name: Install repo packages
  become: true
  dnf:
    state: present
    disable_gpg_check: yes
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Enable GitHub CLI Repo
  become: true
  command: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  args:
    creates: /etc/yum.repos.d/gh-cli.repo

- name: Install common RedHat packages
  become: true
  dnf:
    state: latest
    name:
      - "@development-tools"
      # Apps
      - bat # Cat clone with pretty highlighting
      - ffmpeg
      # - chromium-browser-privacy # https://github.com/Eloston/ungoogled-chromium
      - gh
      - htop
      - ImageMagick
      - maim
      - xclip

- name: Manage flatpak repository remotes
  flatpak_remote:
    state: present
    method: user
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    state: present
    method: user
    remote: flathub
    name: "{{ item }}"
  with_items:
    - org.telegram.desktop
    - org.videolan.VLC
    - com.bluejeans.Bluejeans
    - com.slack.Slack
    - com.spotify.Client
    - us.zoom.Zoom

- name: Link config files into place
  file:
    src: "{{ item }}"
    dest: "{{ xdg_config_home }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/config/*"

- name: Change hostname
  hostname:
    name: "{{ hostname }}"
