---

- name: Copy repos into place
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/files/repos/*"

- name: Install repo packages
  become: true
  dnf:
    state: present
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install common RedHat packages
  become: true
  dnf:
    state: latest
    name:
      - "@development-tools"
      # Apps
      - bat # Cat clone with pretty highlighting
      - ffmpeg
      - chromium-browser-privacy # https://github.com/Eloston/ungoogled-chromium
      - htop
      - ImageMagick
      - NetworkManager-openvpn
      - python3
      - python-pip
      - scrot
      - xbacklight
      - xclip
      - xorg-x11-drv-synaptics-legacy
      - "https://github.com/cli/cli/releases/download/v0.6.4/gh_0.6.4_linux_amd64.rpm" # github cli

- name: Manage flatpak repository remotes
  flatpak_remote:
    state: present
    method: user
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    state: present
    method: user
    remote: flathub
    name: "{{ item }}"
  with_items:
    - org.telegram.desktop
    - org.videolan.VLC
    - com.bluejeans.Bluejeans
    - com.slack.Slack
    - com.spotify.Client
    - us.zoom.Zoom

- name: Link config files into place
  file:
    src: "{{ item }}"
    dest: "{{ xdg_config_home }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/config/*"

- name: Change hostname
  hostname:
    name: "{{ hostname }}"
