---
- name: Install packages
  become: true
  dnf:
    name: znc
    state: latest
  when: ansible_os_family == "RedHat"

- name: Open ports
  become: true
  command: firewall-cmd --add-port 6697/tcp
