#!/usr/bin/env bash

if [ $# -ge 1 ]; then
	if [ $# -gt 1 ]; then
		echo "Can't handle multiple files yet"
		exit 1
	fi

	dir=$( cd "$(dirname $1)" ; pwd -P )
	base=$(basename $1)
	if [[ "$dir" =~ "$PWD" ]]; then
		podman run -it --rm --privileged --volume $PWD:$PWD --workdir $PWD vim -- "$1"
	else
		podman run -it --rm --privileged --volume $dir:$dir --workdir $dir vim -- "$dir/$base"
	fi
else
	podman run -it --rm --privileged --volume $PWD:$PWD --workdir $PWD vim
fi
