---

- name: Install vim
  become: true
  dnf:
    name: vim-X11
    state: latest

- name: Ensure config and cache directories exist
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ vim_config_dir }}"
    - "{{ vim_cache_dir }}"
    - "{{ vim_cache_dir }}/undo"
    - "{{ vim_cache_dir }}/swap"
    - "{{ vim_cache_dir }}/backup"

- name: Link vimrc into place
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ vim_config_dir }}/vimrc"
    force: yes
    state: link
