---

- name: Install gpg2
  become: true
  dnf:
    name:
      - gnupg2
      - pcsc-lite
    state: latest

- name: Ensure config directory exists
  file:
    dest: "{{ gpg_config_dir }}"
    state: directory
    mode: '700'

- name: Link configuration files into place
  file:
    src: "{{ item }}"
    dest: "{{ gpg_config_dir }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: Import public key
  command: gpg --import "{{ role_path }}/files/gpg.pub"

- name: Trust the key
  command: echo -e "5\ny\n" |  gpg --command-fd 0 --expert --edit-key "{{ key_id }}" trust
