---

- name: homebrew | download Homebrew install script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest=vendor/homebrew/install

- name: homebrew | install Homebrew
  command: ruby vendor/homebrew/install creates=/usr/local/bin/brew

- name: homebrew | update Homebrew
  homebrew: update_homebrew=yes

- name: homebrew | brew tap
  homebrew_tap: tap={{item}} state=present
  with_items:
    "{{ brew.taps }}"

- name: homebrew | brew install
  homebrew: formula={{item}} state=latest
  with_items:
    "{{ brew.formulas }}"

- name: homebrew | brew install with options
  homebrew: formula={{item.formula}} install_options={{item.options}} state=latest
  with_items:
    "{{ brew.formulas_opt }}"

- name: homebrew | brew cask
  homebrew_cask: name={{item}} state=present
  with_items:
    "{{ brew.apps }}"

- name: homebrew | install fonts
  homebrew_cask: name={{item}} state=present
  with_items:
    "{{ brew.fonts }}"

- name: homebrew | clean up old versions
  command: brew cleanup

- name: homebrew | clean up old casks
  command: brew cask cleanup

- name: homebrew | remove install script
  file: path=vendor/homebrew/install state=absent
