---

- name: Create directory for nvim archive
  file:
    path: "{{ nvim_data_dir }}"
    state: directory

- name: Get nvim release
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ nvim_version }}/nvim-linux64.tar.gz"
    dest: "{{ nvim_data_dir }}/nvim-{{ nvim_version }}-linux64.tar.gz"
  register: nvim_tar

- name: Unarchive nvim
  unarchive:
    src: "{{ nvim_tar.dest }}"
    dest: "{{ nvim_data_dir }}"
    extra_opts: [--strip-components=1]

- name: Link nvim
  file:
    src: "{{ nvim_data_dir }}/bin/nvim"
    path: "{{ xdg_data_home }}/bin/nvim"
    state: link

- name: Ensure important directories exist
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ nvim_config_dir }}"
    - "{{ nvim_config_dir }}/autoload"

- name: Link init.vim into place
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ nvim_config_dir }}/init.vim"
    force: yes
    state: link

- name: Link personal autoload scripts in
  file:
    src: "{{ role_path }}/files/autoload/dzager"
    dest: "{{ nvim_config_dir }}/autoload/dzager"
    force: yes
    state: link

- name: Link personal config directories in
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ nvim_config_dir }}/{{ item }}"
    force: yes
    state: link
  with_items:
    - ftdetect
    - after
    - plugin
