---

- name: Install
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "RedHat"
  with_items:
    - btrfs-progs-devel
    - device-mapper-devel
    - etcd

# TODO: Need to install oc and glide binaries

# Docker Setup
- name: Add insecure registry
  become: true
  blockinfile:
    path: /etc/sysconfig/docker
    block: |
      # Following Instructions:
      # https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux
      INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16 --insecure-registry asb-registry.usersys.redhat.com:5000'
      DOCKER_NETWORK_OPTIONS='--dns 10.11.5.19 --dns 10.5.30.160'

- name: Restart docker
  become: true
  service:
    name: docker
    daemon_reload: yes
    state: restarted

- name: Get firewall zones
  become: true
  command: firewall-cmd --permanent --get-zones
  register: firewall_zones

- name: Create dockerc firewall zone
  become: true
  command: firewall-cmd --permanent --new-zone dockerc
  when: firewall_zones.stdout.find('dockerc') == -1

- name: Get dockerc sources
  become: true
  command: firewall-cmd --permanent --zone dockerc --list-sources
  register: dockerc_sources

- name: Add dockerc source
  become: true
  command: firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
  when: dockerc_sources.stdout.find('172.17.0.0/16') == -1

- name: Get dockerc ports
  become: true
  command: firewall-cmd --permanent --zone dockerc --list-ports

- name: Add dockerc ports
  become: true
  command: firewall-cmd --permanent --zone dockerc --add-port "{{ item }}"
  when: dockerc_sources.stdout.find( item ) == -1
  with_items:
    - 8443/tcp
    - 53/udp
    - 8053/udp

- name: Reload firewall rules
  become: true
  command: firewall-cmd --reload

# Minishift + Minikube
- name: Get docker kvm plugin
  become: true
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
    dest: /usr/local/bin/docker-machine-driver-kvm2
    mode: +x

- name: Add self to libvirt group
  become: true
  user:
      name: "{{ ansible_user_id }}"
      groups: libvirt
      append: yes

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: "{{ ansible_user_dir }}/bin/minikube"
    mode: +x
