---

- name: Install fonts
  become: true
  dnf:
    state: latest
    name:
      # Fonts
      - adobe-source-code-pro-fonts
      - dejavu-sans-mono-fonts
      - google-droid-sans-mono-fonts
      - google-noto-emoji-fonts
      - levien-inconsolata-fonts
      - mozilla-fira-mono-fonts

- name: Ensure font directory exists
  file:
    dest: "{{ font_dir }}"
    state: directory

# https://www.nerdfonts.com/
- name: Link fonts
  file:
    src: "{{ item }}"
    dest: "{{ font_dir }}/{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ role_path }}/files/*.ttf"

